export type ItemSlot =
  | 'Main Hand'
  | 'Off Hand'
  | 'Chest'
  | 'Helmet'
  | 'Gloves'
  | 'Boots'
  | 'Ring'
  | 'Bracer'
  | 'Necklace'
  | 'Earring'

export type ItemRarity =
  | 'Common'
  | 'Uncommon'
  | 'Rare'
  | 'Epic'
  | 'Legendary'
  | 'Mythic'
  | 'Astral'
  | 'Cosmic'

export type ItemType =
  'Weapon' | 'Armor' | 'Accessory' | 'Material' | 'Gem' | 'Engraving' | 'Potion'

export const SLOT_ORDER: ItemSlot[] = [
  'Main Hand',
  'Off Hand',
  'Chest',
  'Helmet',
  'Gloves',
  'Boots',
  'Ring',
  'Bracer',
  'Necklace',
  'Earring',
]

export const RARITY_COLORS: Record<ItemRarity, string> = {
  Common: 'text-gray-300 border-gray-500',
  Uncommon: 'text-green-400 border-green-500',
  Rare: 'text-blue-400 border-blue-500',
  Epic: 'text-purple-400 border-purple-500',
  Legendary: 'text-orange-400 border-orange-500',
  Mythic: 'text-red-400 border-red-500',
  Astral: 'text-pink-400 border-pink-500',
  Cosmic: 'text-yellow-300 border-yellow-500',
}

export const RARITY_BG: Record<ItemRarity, string> = {
  Common: 'bg-gray-800/40',
  Uncommon: 'bg-green-900/30',
  Rare: 'bg-blue-900/30',
  Epic: 'bg-purple-900/30',
  Legendary: 'bg-orange-900/30',
  Mythic: 'bg-red-900/30',
  Astral: 'bg-pink-900/30',
  Cosmic: 'bg-yellow-900/30',
}

export const RARITY_MULTIPLIERS: Record<ItemRarity, number> = {
  Common: 1,
  Uncommon: 1.5,
  Rare: 2.5,
  Epic: 4,
  Legendary: 7,
  Mythic: 11,
  Astral: 16,
  Cosmic: 23,
}

export const SOCKET_LIMIT: Record<ItemRarity, number> = {
  Common: 0,
  Uncommon: 1,
  Rare: 1,
  Epic: 2,
  Legendary: 2,
  Mythic: 2,
  Astral: 2,
  Cosmic: 2,
}

export const ITEM_DATABASE = {
  weapons: {
    'Rusty Sword': {
      slot: 'Main Hand' as ItemSlot,
      type: 'Weapon' as ItemType,
      rarity: 'Common' as ItemRarity,
      atk: 5,
      def: 0,
      hp: 0,
      spd: 0,
    },
    'Steel Blade': {
      slot: 'Main Hand' as ItemSlot,
      type: 'Weapon' as ItemType,
      rarity: 'Uncommon' as ItemRarity,
      atk: 15,
      def: 0,
      hp: 0,
      spd: 0,
    },
    'Flame Sword': {
      slot: 'Main Hand' as ItemSlot,
      type: 'Weapon' as ItemType,
      rarity: 'Rare' as ItemRarity,
      atk: 30,
      def: 0,
      hp: 0,
      spd: 0,
    },
    'Void Cleaver': {
      slot: 'Main Hand' as ItemSlot,
      type: 'Weapon' as ItemType,
      rarity: 'Epic' as ItemRarity,
      atk: 55,
      def: 0,
      hp: 0,
      spd: 0,
    },
    'Dragon Slayer': {
      slot: 'Main Hand' as ItemSlot,
      type: 'Weapon' as ItemType,
      rarity: 'Legendary' as ItemRarity,
      atk: 90,
      def: 0,
      hp: 0,
      spd: 0,
    },
    'Cosmic Edge': {
      slot: 'Main Hand' as ItemSlot,
      type: 'Weapon' as ItemType,
      rarity: 'Cosmic' as ItemRarity,
      atk: 150,
      def: 0,
      hp: 0,
      spd: 0,
    },
    'Wooden Shield': {
      slot: 'Off Hand' as ItemSlot,
      type: 'Weapon' as ItemType,
      rarity: 'Common' as ItemRarity,
      atk: 0,
      def: 8,
      hp: 0,
      spd: 0,
    },
    'Iron Shield': {
      slot: 'Off Hand' as ItemSlot,
      type: 'Weapon' as ItemType,
      rarity: 'Uncommon' as ItemRarity,
      atk: 0,
      def: 18,
      hp: 0,
      spd: 0,
    },
    Aegis: {
      slot: 'Off Hand' as ItemSlot,
      type: 'Weapon' as ItemType,
      rarity: 'Epic' as ItemRarity,
      atk: 0,
      def: 40,
      hp: 0,
      spd: 0,
    },
    'Celestial Ward': {
      slot: 'Off Hand' as ItemSlot,
      type: 'Weapon' as ItemType,
      rarity: 'Legendary' as ItemRarity,
      atk: 0,
      def: 70,
      hp: 0,
      spd: 0,
    },
  },
  armor: {
    'Cloth Robe': {
      slot: 'Chest' as ItemSlot,
      type: 'Armor' as ItemType,
      rarity: 'Common' as ItemRarity,
      atk: 0,
      def: 3,
      hp: 10,
      spd: 0,
    },
    'Leather Vest': {
      slot: 'Chest' as ItemSlot,
      type: 'Armor' as ItemType,
      rarity: 'Uncommon' as ItemRarity,
      atk: 0,
      def: 8,
      hp: 25,
      spd: 0,
    },
    Chainmail: {
      slot: 'Chest' as ItemSlot,
      type: 'Armor' as ItemType,
      rarity: 'Rare' as ItemRarity,
      atk: 0,
      def: 18,
      hp: 50,
      spd: 0,
    },
    'Plate Armor': {
      slot: 'Chest' as ItemSlot,
      type: 'Armor' as ItemType,
      rarity: 'Epic' as ItemRarity,
      atk: 0,
      def: 35,
      hp: 90,
      spd: 0,
    },
    'Dragon Scale': {
      slot: 'Chest' as ItemSlot,
      type: 'Armor' as ItemType,
      rarity: 'Legendary' as ItemRarity,
      atk: 0,
      def: 60,
      hp: 150,
      spd: 0,
    },
    'Iron Helm': {
      slot: 'Helmet' as ItemSlot,
      type: 'Armor' as ItemType,
      rarity: 'Common' as ItemRarity,
      atk: 0,
      def: 2,
      hp: 5,
      spd: 0,
    },
    'Knight Helm': {
      slot: 'Helmet' as ItemSlot,
      type: 'Armor' as ItemType,
      rarity: 'Uncommon' as ItemRarity,
      atk: 0,
      def: 6,
      hp: 12,
      spd: 0,
    },
    'Crown of Frost': {
      slot: 'Helmet' as ItemSlot,
      type: 'Armor' as ItemType,
      rarity: 'Epic' as ItemRarity,
      atk: 0,
      def: 15,
      hp: 30,
      spd: 0,
    },
    'Mythril Helm': {
      slot: 'Helmet' as ItemSlot,
      type: 'Armor' as ItemType,
      rarity: 'Legendary' as ItemRarity,
      atk: 0,
      def: 25,
      hp: 55,
      spd: 0,
    },
    'Leather Gloves': {
      slot: 'Gloves' as ItemSlot,
      type: 'Armor' as ItemType,
      rarity: 'Common' as ItemRarity,
      atk: 1,
      def: 1,
      hp: 0,
      spd: 2,
    },
    'War Gauntlets': {
      slot: 'Gloves' as ItemSlot,
      type: 'Armor' as ItemType,
      rarity: 'Uncommon' as ItemRarity,
      atk: 3,
      def: 3,
      hp: 0,
      spd: 5,
    },
    'Thunder Grip': {
      slot: 'Gloves' as ItemSlot,
      type: 'Armor' as ItemType,
      rarity: 'Rare' as ItemRarity,
      atk: 8,
      def: 5,
      hp: 0,
      spd: 12,
    },
    'Void Grasp': {
      slot: 'Gloves' as ItemSlot,
      type: 'Armor' as ItemType,
      rarity: 'Epic' as ItemRarity,
      atk: 15,
      def: 10,
      hp: 0,
      spd: 20,
    },
    Sandals: {
      slot: 'Boots' as ItemSlot,
      type: 'Armor' as ItemType,
      rarity: 'Common' as ItemRarity,
      atk: 0,
      def: 1,
      hp: 0,
      spd: 3,
    },
    'Iron Boots': {
      slot: 'Boots' as ItemSlot,
      type: 'Armor' as ItemType,
      rarity: 'Uncommon' as ItemRarity,
      atk: 0,
      def: 4,
      hp: 0,
      spd: 6,
    },
    'Wind Runners': {
      slot: 'Boots' as ItemSlot,
      type: 'Armor' as ItemType,
      rarity: 'Rare' as ItemRarity,
      atk: 0,
      def: 6,
      hp: 0,
      spd: 15,
    },
    'Phoenix Greaves': {
      slot: 'Boots' as ItemSlot,
      type: 'Armor' as ItemType,
      rarity: 'Epic' as ItemRarity,
      atk: 0,
      def: 10,
      hp: 0,
      spd: 25,
    },
  },
  accessories: {
    'Copper Ring': {
      slot: 'Ring' as ItemSlot,
      type: 'Accessory' as ItemType,
      rarity: 'Common' as ItemRarity,
      atk: 2,
      def: 2,
      hp: 5,
      spd: 0,
    },
    'Silver Ring': {
      slot: 'Ring' as ItemSlot,
      type: 'Accessory' as ItemType,
      rarity: 'Uncommon' as ItemRarity,
      atk: 5,
      def: 5,
      hp: 12,
      spd: 0,
    },
    'Gold Ring': {
      slot: 'Ring' as ItemSlot,
      type: 'Accessory' as ItemType,
      rarity: 'Rare' as ItemRarity,
      atk: 10,
      def: 10,
      hp: 25,
      spd: 0,
    },
    'Diamond Ring': {
      slot: 'Ring' as ItemSlot,
      type: 'Accessory' as ItemType,
      rarity: 'Epic' as ItemRarity,
      atk: 18,
      def: 18,
      hp: 45,
      spd: 0,
    },
    'Cosmic Band': {
      slot: 'Ring' as ItemSlot,
      type: 'Accessory' as ItemType,
      rarity: 'Legendary' as ItemRarity,
      atk: 30,
      def: 30,
      hp: 70,
      spd: 0,
    },
    'Leather Bracer': {
      slot: 'Bracer' as ItemSlot,
      type: 'Accessory' as ItemType,
      rarity: 'Common' as ItemRarity,
      atk: 1,
      def: 3,
      hp: 0,
      spd: 0,
    },
    'Steel Bracer': {
      slot: 'Bracer' as ItemSlot,
      type: 'Accessory' as ItemType,
      rarity: 'Uncommon' as ItemRarity,
      atk: 3,
      def: 7,
      hp: 0,
      spd: 0,
    },
    'Reinforced Bracer': {
      slot: 'Bracer' as ItemSlot,
      type: 'Accessory' as ItemType,
      rarity: 'Rare' as ItemRarity,
      atk: 6,
      def: 14,
      hp: 0,
      spd: 0,
    },
    'Titan Bracer': {
      slot: 'Bracer' as ItemSlot,
      type: 'Accessory' as ItemType,
      rarity: 'Epic' as ItemRarity,
      atk: 12,
      def: 25,
      hp: 0,
      spd: 0,
    },
    'Bronze Necklace': {
      slot: 'Necklace' as ItemSlot,
      type: 'Accessory' as ItemType,
      rarity: 'Common' as ItemRarity,
      atk: 2,
      def: 2,
      hp: 8,
      spd: 0,
    },
    'Gold Pendant': {
      slot: 'Necklace' as ItemSlot,
      type: 'Accessory' as ItemType,
      rarity: 'Uncommon' as ItemRarity,
      atk: 5,
      def: 5,
      hp: 18,
      spd: 0,
    },
    'Emerald Amulet': {
      slot: 'Necklace' as ItemSlot,
      type: 'Accessory' as ItemType,
      rarity: 'Rare' as ItemRarity,
      atk: 10,
      def: 10,
      hp: 35,
      spd: 0,
    },
    'Ruby Talisman': {
      slot: 'Necklace' as ItemSlot,
      type: 'Accessory' as ItemType,
      rarity: 'Epic' as ItemRarity,
      atk: 18,
      def: 18,
      hp: 60,
      spd: 0,
    },
    'Wooden Earring': {
      slot: 'Earring' as ItemSlot,
      type: 'Accessory' as ItemType,
      rarity: 'Common' as ItemRarity,
      atk: 1,
      def: 1,
      hp: 3,
      spd: 0,
    },
    'Silver Earring': {
      slot: 'Earring' as ItemSlot,
      type: 'Accessory' as ItemType,
      rarity: 'Uncommon' as ItemRarity,
      atk: 3,
      def: 3,
      hp: 8,
      spd: 0,
    },
    'Gold Earring': {
      slot: 'Earring' as ItemSlot,
      type: 'Accessory' as ItemType,
      rarity: 'Rare' as ItemRarity,
      atk: 6,
      def: 6,
      hp: 15,
      spd: 0,
    },
    'Diamond Stud': {
      slot: 'Earring' as ItemSlot,
      type: 'Accessory' as ItemType,
      rarity: 'Epic' as ItemRarity,
      atk: 12,
      def: 12,
      hp: 28,
      spd: 0,
    },
  },
}

export const ALL_ITEMS = Object.values(ITEM_DATABASE).flatMap((group) =>
  Object.entries(group).map(([name, item]) => ({ name, ...item })),
)
